[package]
name = "symscan-py"
authors = ["Yuta Nagano"]
version = "0.6.1"
edition = "2021"
description = "Python bindings for symscan"

[dependencies]
symscan = { version = "0.6.1", path = "../symscan/" }
pyo3 = "0.27"
numpy = "0.27"

[lib]
crate-type = ["cdylib"]
